clear;
bin_file_name = 'short_throw_depth_camera_space_projection.bin';
bin_file_name1 = 'short_throw_depth_camera_space_projection1.bin';
bin_file = fopen(bin_file_name, 'r');
bin_file1 = fopen(bin_file_name1, 'r');
[data, num] = fread(bin_file, 'float32');
[data1, num1] = fread(bin_file1, 'float32');
judge = (data == data1);
[X,Y] = find(judge == 0);
fclose(bin_file);
fclose(bin_file1);